import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";

import "@xyflow/react/dist/style.css";
import "./react-flow.css";
import "./globals.css";

const sans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const mono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sans.variable} ${sans.className} ${mono.variable} dark`}>{children}</body>
    </html>
  );
}
